language: clojure

jdk:
  - openjdk8

env:
  global:
   - ES_PATH_CONF=/tmp/

install:
    - mkdir /tmp/elasticsearch
    - mkdir /tmp/restore
    - mkdir /tmp/data
    - cp test/resources/elasticsearch.yml /tmp/
    - cp test/resources/jvm.options /tmp/
    - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.0-linux-x86_64.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
    - /tmp/elasticsearch/bin/elasticsearch --daemonize

before_script:
  - sleep 60
  - curl http://127.0.0.1:9200/

script:
  - lein travis
